services:
    nginx:
      image: nginx:latest
      ports:
        - "443:443"

      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./certs:/etc/nginx/certs:ro
      depends_on:
        - apache
        - apache_backup
      networks:
        - mynet

    apache:
      image: httpd:latest
      ports:
        - "8008:80"
      volumes:
        - ./html_apache:/usr/local/apache2/htdocs/
      networks:
        - mynet

    apache_backup:
      image: httpd:latest
      ports:
        - "8080:80"
      volumes:
        - ./html_backup:/usr/local/apache2/htdocs/
      networks:
        - mynet
networks:
  mynet: